# Generated by Django 4.1.7 on 2023-05-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_panier_contenupanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
